Music organization (kog patch 20)
shoc71/Keep-On-Going pull request #332
Opened 2023-09-22 19:57 UTC by shoc71

- readme created audio folders
- rearranged the audio files
- changed readme for general instructions of the game

2023-09-23 23:45 UTC, slysnivy requested changes
The README's title is incorrect because it should be "Keep On Going"

2023-09-24 00:59 UTC, shoc71 commented
It is.

2023-09-25 20:49 UTC, slysnivy approved these changes

2023-09-25 20:50 UTC, slysnivy commented
I've fixed the readme title

2023-09-25 20:50 UTC, merged